# Generated by Django 4.2.1 on 2023-05-23 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahome', '0003_ibju_alter_pjmanage_optcode_alter_pjmanage_pjname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Const',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('기준월', models.DateField(blank=True, null=True)),
                ('지수', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Onsale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('시도자치구', models.CharField(max_length=20)),
                ('시도', models.CharField(blank=True, max_length=20, null=True)),
                ('자치구', models.CharField(blank=True, max_length=20, null=True)),
                ('미분양', models.IntegerField()),
                ('기준월', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pjcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('구분', models.CharField(blank=True, max_length=2, null=True)),
                ('코드', models.CharField(blank=True, max_length=5, null=True)),
                ('내역', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('시도자치구', models.CharField(max_length=20)),
                ('시도', models.CharField(blank=True, max_length=20, null=True)),
                ('자치구', models.CharField(blank=True, max_length=20, null=True)),
                ('총인구수', models.IntegerField()),
                ('세대수', models.IntegerField()),
                ('기준월', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
