# Generated by Django 4.2.1 on 2023-05-30 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahome', '0004_const_onsale_pjcode_pop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rtech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('시도', models.CharField(blank=True, max_length=20, null=True)),
                ('자치구', models.CharField(blank=True, max_length=20, null=True)),
                ('아파트', models.CharField(blank=True, max_length=50, null=True)),
                ('주소', models.CharField(blank=True, max_length=50, null=True)),
                ('평당가', models.IntegerField()),
                ('국평가격', models.IntegerField()),
            ],
        ),
    ]
