# Generated by Django 4.2.1 on 2023-05-31 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bunyang',
            name='구분',
        ),
        migrations.RemoveField(
            model_name='bunyang',
            name='시군구',
        ),
        migrations.RemoveField(
            model_name='bunyang',
            name='지역코드',
        ),
        migrations.AddField(
            model_name='bunyang',
            name='건축년도',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
