# Generated by Django 4.2.1 on 2023-05-31 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rtp', '0002_remove_bunyang_구분_remove_bunyang_시군구_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bunyang',
            name='거래금액',
        ),
        migrations.RemoveField(
            model_name='bunyang',
            name='거래유형',
        ),
        migrations.RemoveField(
            model_name='bunyang',
            name='건축년도',
        ),
        migrations.RemoveField(
            model_name='bunyang',
            name='기준월',
        ),
        migrations.RemoveField(
            model_name='bunyang',
            name='년',
        ),
        migrations.RemoveField(
            model_name='bunyang',
            name='법정동',
        ),
        migrations.RemoveField(
            model_name='bunyang',
            name='시자치구',
        ),
        migrations.RemoveField(
            model_name='bunyang',
            name='아파트',
        ),
        migrations.RemoveField(
            model_name='bunyang',
            name='월',
        ),
        migrations.RemoveField(
            model_name='bunyang',
            name='전용',
        ),
        migrations.RemoveField(
            model_name='bunyang',
            name='전용면적',
        ),
        migrations.RemoveField(
            model_name='bunyang',
            name='층',
        ),
    ]
