# Generated by Django 4.2.1 on 2023-05-31 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtp', '0003_remove_bunyang_거래금액_remove_bunyang_거래유형_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bunyang',
            name='거래금액',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bunyang',
            name='거래유형',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bunyang',
            name='건축년도',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bunyang',
            name='기준월',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bunyang',
            name='년',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bunyang',
            name='법정동',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bunyang',
            name='시자치구',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bunyang',
            name='아파트',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bunyang',
            name='월',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bunyang',
            name='전용',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bunyang',
            name='전용면적',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bunyang',
            name='층',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
