# Generated by Django 4.2.1 on 2023-05-31 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rtp', '0004_bunyang_거래금액_bunyang_거래유형_bunyang_건축년도_bunyang_기준월_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bunyang',
            name='건축년도',
        ),
    ]
