# Generated by Django 4.2.1 on 2023-06-01 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_brand_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viewimage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pj', models.CharField(blank=True, max_length=30, null=True)),
                ('view_img', models.ImageField(upload_to='')),
            ],
        ),
    ]
